//! Raw FFI bindings to FFmpeg/libav libraries.
//!
//! This crate provides unsafe, low-level bindings generated by bindgen.
//! For safe abstractions, use the `ffmpeg` crate.

#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(clippy::all)]
#![allow(dead_code)]

mod bindings {
    include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
}

pub use bindings::*;

// Re-export common error codes for convenience
pub const AVERROR_EOF: i32 =
    -(b'E' as i32 | (b'O' as i32) << 8 | (b'F' as i32) << 16 | (b' ' as i32) << 24);
pub const AVERROR_EAGAIN: i32 = -11; // EAGAIN on most Unix systems

/// Helper to create AVERROR from POSIX error code
#[inline]
pub const fn averror(e: i32) -> i32 {
    -e
}

/// Helper to get POSIX error code from AVERROR
#[inline]
pub const fn avunerror(e: i32) -> i32 {
    -e
}

/// Check if error code indicates "try again"
#[inline]
pub fn is_eagain(err: i32) -> bool {
    err == AVERROR_EAGAIN || err == averror(libc::EAGAIN)
}

/// Check if error code indicates end of file
#[inline]
pub fn is_eof(err: i32) -> bool {
    err == AVERROR_EOF
}
